### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by violet4** [mica5/mathquill-standalone#2]
change frames.html to mathquill.html in "run by opening frames.html in a web browser."
also cite detexify in the readme:
Detexify courtesy of Daniel Kirsch and Philipp Kühl at http://detexify.kirelabs.org/classify.html

**Comment by mica5** [comment]
also cite detexify in the readme:
Detexify courtesy of Daniel Kirsch and Philipp Kühl at http://detexify.kirelabs.org/classify.html

**Comment by violet4** [comment]
issue cleanup
